### ISSUE TITLE
게시글 View & 게시글 CRUD

### ISSUE THREAD

**Issue by songhaechan** [SQUAD-D/board#4]
## Discription
게시글 View 구현 및 CRUD 구현
## Todo
- [x] 메인화면 CSS,JS 적용 (간단한 디자인)
- [ ] 게시글 생성 View
- [ ] 게시글 조회 View
- [ ] 게시글 수정 View
- [ ] 게시글 CRUD
